-- ==============================================================================
-- Migration V1: Baseline Schema
-- Criação das 7 tabelas estruturais da aplicação e seus relacionamentos base.
-- ==============================================================================

-- 1. Tabela de Usuários
CREATE TABLE IF NOT EXISTS public.usuarios (
    id_usuario BIGINT NOT NULL,
    nome_usuario VARCHAR(80) NOT NULL,
    email_usuario VARCHAR(100) NOT NULL,
    senha_usuario VARCHAR(255) NOT NULL,
    phone_usuario VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT true,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuarios_email UNIQUE (email_usuario),
    CONSTRAINT usuarios_role_check CHECK (role IN ('CLIENT', 'ADMIN'))
);

CREATE SEQUENCE IF NOT EXISTS public.usuarios_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- 2. Tabela de Quadras
CREATE TABLE IF NOT EXISTS public.quadras (
    id_quadra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    tipo_esporte VARCHAR(30) NOT NULL,
    valor_hora NUMERIC(10, 2) NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT true,
    cep VARCHAR(9),
    logradouro VARCHAR(255),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado VARCHAR(2),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    descricao TEXT,
    data_limite_agendamento DATE,
    admin_id BIGINT,
    CONSTRAINT quadras_tipo_esporte_check CHECK (tipo_esporte IN ('FUTEBOL', 'FUTSAL', 'VOLEI', 'BEACH_TENNIS', 'BASQUETE', 'TENIS')),
    CONSTRAINT fk_quadras_admin FOREIGN KEY (admin_id) REFERENCES public.usuarios(id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_quadra_admin ON public.quadras (admin_id);
CREATE INDEX IF NOT EXISTS idx_quadra_ativa ON public.quadras (ativa);
CREATE INDEX IF NOT EXISTS idx_quadras_lat_lng ON public.quadras (latitude, longitude);

-- 3. Fotos das Quadras
CREATE TABLE IF NOT EXISTS public.quadra_fotos (
    quadra_id BIGINT NOT NULL,
    foto_url VARCHAR(255),
    CONSTRAINT fk_quadra_fotos_quadra FOREIGN KEY (quadra_id) REFERENCES public.quadras(id_quadra) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_quadra_fotos_quadra_id ON public.quadra_fotos (quadra_id);

-- 4. Disponibilidades Semanais das Quadras
CREATE TABLE IF NOT EXISTS public.quadra_disponibilidades (
    quadra_id BIGINT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    hora_inicio TIME WITHOUT TIME ZONE NOT NULL,
    hora_fim TIME WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_quadra_disponibilidades_quadra FOREIGN KEY (quadra_id) REFERENCES public.quadras(id_quadra) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_quadra_disp_quadra_id ON public.quadra_disponibilidades (quadra_id);

-- 5. Bloqueios de Horário
CREATE TABLE IF NOT EXISTS public.quadra_bloqueios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quadra_id BIGINT NOT NULL,
    data DATE NOT NULL,
    hora_inicio TIME WITHOUT TIME ZONE,
    hora_fim TIME WITHOUT TIME ZONE,
    motivo VARCHAR(255),
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_quadra_bloqueios_quadra FOREIGN KEY (quadra_id) REFERENCES public.quadras(id_quadra) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bloqueio_quadra_data ON public.quadra_bloqueios (quadra_id, data);

-- 6. Notificações
CREATE TABLE IF NOT EXISTS public.notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    mensagem VARCHAR(255) NOT NULL,
    lida BOOLEAN NOT NULL DEFAULT false,
    excluida BOOLEAN NOT NULL DEFAULT false,
    data_criacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_notificacoes_admin FOREIGN KEY (admin_id) REFERENCES public.usuarios(id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_notificacoes_admin_data ON public.notificacoes (admin_id, data_criacao DESC);

-- 7. Agendamentos
CREATE TABLE IF NOT EXISTS public.agendamentos (
    id_agendamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    quadra_id BIGINT NOT NULL,
    data_hora_inicio TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_hora_fim TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    valor_total NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    transacao_pagamento_id VARCHAR(100),
    pix_copiaecola TEXT,
    qr_code_base64 TEXT,
    criado_em TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    cancelado_em TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT agendamentos_status_check CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO')),
    CONSTRAINT fk_agendamentos_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario),
    CONSTRAINT fk_agendamentos_quadra FOREIGN KEY (quadra_id) REFERENCES public.quadras(id_quadra)
);

CREATE INDEX IF NOT EXISTS idx_agendamento_quadra_data ON public.agendamentos (quadra_id, data_hora_inicio, data_hora_fim);
CREATE INDEX IF NOT EXISTS idx_agendamento_usuario ON public.agendamentos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_agendamento_status ON public.agendamentos (status);
